services:
  db:
    image: postgres:15
    container_name: nba_stats_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./csv:/csv
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s

  init:
    image: postgres:15
    container_name: nba_stats_init
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./init-db.sh:/init-db.sh
      - ./csv:/csv
    entrypoint: ["/bin/bash", "/init-db.sh"]
    restart: "no"

volumes:
  pgdata:
