services:
  db:
    image: postgres:latest
    container_name: nba_stats_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
